-- 06_seed_basic_data.sql
-- This script seeds the database with a sample organization and a test user.

-- Ensure pgcrypto extension is available for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Create a sample organization
INSERT INTO public.organizations (name) VALUES ('Test University') ON CONFLICT (name) DO NOTHING;

-- Retrieve the ID of the organization (optional, if needed for other relations)
-- SELECT id INTO current_organization_id FROM public.organizations WHERE name = 'Test University';

-- 2. Define the schema name based on the organization name
-- For simplicity, we'll replace spaces and convert to lowercase.
-- PostgreSQL schema names should be valid identifiers.
-- 'Test University' becomes 'test_university'
DO $$
DECLARE
  org_name TEXT := 'Test University';
  schema_name TEXT := lower(replace(org_name, ' ', '_'));
  user_email TEXT := 'testuser@example.com';
  -- Bcrypt hash for 'password123'.
  -- In a real application, this hash would be generated by the backend during user creation.
  -- This is a known example hash for 'password123': $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
  user_password_hash TEXT := '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';
BEGIN
  -- 3. Create a schema for the organization if it doesn't exist
  EXECUTE 'CREATE SCHEMA IF NOT EXISTS ' || quote_ident(schema_name);

  -- 4. Create the users table within the organization's schema
  -- This structure is based on 03_create_users_table_template.sql
  EXECUTE 'CREATE TABLE IF NOT EXISTS ' || quote_ident(schema_name) || '.users (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL DEFAULT ''normal'',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )';

  -- 5. Create an index on the email column for faster lookups
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_email ON ' || quote_ident(schema_name) || '.users(email)';

  -- 6. Insert a sample user into the new users table
  -- Use ON CONFLICT to avoid errors if the script is run multiple times, though email should be unique.
  EXECUTE 'INSERT INTO ' || quote_ident(schema_name) || '.users (email, password_hash, role) VALUES ($1, $2, $3) ON CONFLICT (email) DO NOTHING'
  USING user_email, user_password_hash, 'admin'; -- Assigning 'admin' role for testing purposes

  RAISE NOTICE 'Successfully seeded data for organization: %', org_name;
  RAISE NOTICE 'Created schema: %', schema_name;
  RAISE NOTICE 'Created user: % in schema %', user_email, schema_name;

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'Error during seeding: %', SQLERRM;
END $$;

-- Instructions to run this script (add these to backend/README.md):
-- After setting up the database and creating the main 'organizations' table,
-- connect to your database (e.g., using psql) and run this script:
--
-- psql -U your_db_user -d your_database_name -f db_scripts/06_seed_basic_data.sql
--
-- Example:
-- psql -U myuser -d library_system -f db_scripts/06_seed_basic_data.sql
--
-- This will create 'Test University', its schema 'test_university',
-- and a user 'testuser@example.com' with password 'password123'.
```
